language: node_js
node_js:
  - "0.10"

# http://rkh.github.io/travis-encrypt/public/index.html
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html

notifications:
  email:
    recipients:
      secure: Cc8afTsDQuKZBOP++FDqKFrD51saQnshUPBreTk+MCBQenksf7zq9w2Pt47EWqKKYB7HSKAwyb3EraUfv5UqoEFOm3bqmHSICUY3XOntRx+zBby/mlkvc6Qs67270hk7GqUWlSwX013sHSyqxZADRipAYf/GMfEYsbQ56vEyg8Y=
    on_success: always # change
    on_failure: always

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  #- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
